spring.application.name=attendanceclient

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/demo
spring.datasource.username=postgres
spring.datasource.password=#FORpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configure the default Eureka server URL for client registration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Optional: Register the service using its IP address rather than hostname
eureka.instance.prefer-ip-address=true
# Disable automated documentation for Spring Data REST repositories
springdoc.show-data-rest=false

